/**
 * Sample points along the lines of a candidate grid, generated by the same
 * drawers that render the grid so detection and rendering can never disagree.
 */

import type { GridType } from '../../grid/GridSystem';
import { drawSquareGrid } from '../../grid/squareGridDrawer';
import { drawHexGrid } from '../../grid/hexGridDrawer';
import { createHexLayout, isHexGridType } from '../../grid/hexGeometry';
import type { GridBounds, GridPath } from '../../grid/gridLineStyle';

export interface LineSample {
  x: number;
  y: number;
  /** Unit normal of the line at this point. */
  nx: number;
  ny: number;
}

interface Segment {
  x1: number;
  y1: number;
  x2: number;
  y2: number;
}

function collectSegments(gridType: GridType, cellSize: number, offsetX: number, offsetY: number, bounds: GridBounds): Segment[] {
  const segments: Segment[] = [];
  let cursor = { x: 0, y: 0 };
  const recorder: GridPath = {
    moveTo(x, y) {
      cursor = { x, y };
      return recorder;
    },
    lineTo(x, y) {
      segments.push({ x1: cursor.x, y1: cursor.y, x2: x, y2: y });
      cursor = { x, y };
      return recorder;
    },
    poly() {
      // Markers are not part of the line template.
      return recorder;
    },
  };

  if (isHexGridType(gridType)) {
    drawHexGrid(recorder, bounds, createHexLayout(gridType, cellSize, offsetX, offsetY), 'solid');
  } else {
    drawSquareGrid(recorder, bounds, cellSize, offsetX, offsetY, 'solid');
  }
  return segments;
}

/**
 * Points every `spacing` pixels along all grid lines inside `bounds`, in the
 * same coordinate space as `bounds` and the offsets.
 */
export function gridLineSamples(
  gridType: GridType,
  cellSize: number,
  offsetX: number,
  offsetY: number,
  bounds: GridBounds,
  spacing: number,
): LineSample[] {
  const samples: LineSample[] = [];
  for (const s of collectSegments(gridType, cellSize, offsetX, offsetY, bounds)) {
    const dx = s.x2 - s.x1;
    const dy = s.y2 - s.y1;
    const length = Math.hypot(dx, dy);
    if (length < spacing / 2) continue;
    const nx = -dy / length;
    const ny = dx / length;
    const count = Math.max(1, Math.floor(length / spacing));
    for (let i = 0; i < count; i++) {
      const t = (i + 0.5) / count;
      samples.push({
        x: bounds.minX + s.x1 + dx * t,
        y: bounds.minY + s.y1 + dy * t,
        nx,
        ny,
      });
    }
  }
  return samples;
}
